In [4]:
from herbie import Herbie, FastHerbie
import pandas as pd, numpy as np
import xarray as xr
import dask

# Fast Herbie

In [2]:
#Date range for FastHerbie
DATES = pd.date_range(
    start="2021-10-07 00:00",
    periods=41,
    freq="6h",
)

# Create a range of forecast lead times
fxx = list(range(0, 24))

DATES, fxx

(DatetimeIndex(['2021-10-07 00:00:00', '2021-10-07 06:00:00',
                '2021-10-07 12:00:00', '2021-10-07 18:00:00',
                '2021-10-08 00:00:00', '2021-10-08 06:00:00',
                '2021-10-08 12:00:00', '2021-10-08 18:00:00',
                '2021-10-09 00:00:00', '2021-10-09 06:00:00',
                '2021-10-09 12:00:00', '2021-10-09 18:00:00',
                '2021-10-10 00:00:00', '2021-10-10 06:00:00',
                '2021-10-10 12:00:00', '2021-10-10 18:00:00',
                '2021-10-11 00:00:00', '2021-10-11 06:00:00',
                '2021-10-11 12:00:00', '2021-10-11 18:00:00',
                '2021-10-12 00:00:00', '2021-10-12 06:00:00',
                '2021-10-12 12:00:00', '2021-10-12 18:00:00',
                '2021-10-13 00:00:00', '2021-10-13 06:00:00',
                '2021-10-13 12:00:00', '2021-10-13 18:00:00',
                '2021-10-14 00:00:00', '2021-10-14 06:00:00',
                '2021-10-14 12:00:00', '2021-10-14 18:00:00',
                '2021-10-15 00:00:00', '2021-10-15 06:00:00',
                '2021-10-15 12:00:00', '2021-10-15 18:00:00',
                '2021-10-16 00:00:00', '2021-10-16 06:00:00',
                '2021-10-16 12:00:00', '2021-10-16 18:00:00',
                '2021-10-17 00:00:00'],
               dtype='datetime64[ns]', freq='6h'),
 [0,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  10,
  11,
  12,
  13,
  14,
  15,
  16,
  17,
  18,
  19,
  20,
  21,
  22,
  23])

In [3]:
FH = FastHerbie(DATES, model="hrrr", fxx=fxx)
FH

In [5]:
FH.objects, len(FH.objects)

([▌▌Herbie HRRR model sfc product initialized 2021-Oct-07 00:00 UTC F00 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-07 00:00 UTC F01 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-07 00:00 UTC F02 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-07 00:00 UTC F03 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-07 00:00 UTC F04 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-07 00:00 UTC F05 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-07 00:00 UTC F06 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-07 00:00 UTC F07 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-07 00:00 UTC F08 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-07 00:00 UTC F09 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-07 00:00 UTC F10 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-07 00:00 UTC F11 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-07 00:00 UTC F12 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-07 00:00 UTC F13 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-07 00:00 UTC F14 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-07 00:00 UTC F15 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-07 00:00 UTC F16 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-07 00:00 UTC F17 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-07 00:00 UTC F18 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-07 00:00 UTC F19 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-07 00:00 UTC F20 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-07 00:00 UTC F21 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-07 00:00 UTC F22 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-07 00:00 UTC F23 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-07 06:00 UTC F00 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-07 06:00 UTC F01 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-07 06:00 UTC F02 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-07 06:00 UTC F03 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-07 06:00 UTC F04 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-07 06:00 UTC F05 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-07 06:00 UTC F06 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-07 06:00 UTC F07 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-07 06:00 UTC F08 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-07 06:00 UTC F09 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-07 06:00 UTC F10 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-07 06:00 UTC F11 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-07 06:00 UTC F12 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-07 06:00 UTC F13 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-07 06:00 UTC F14 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-07 06:00 UTC F15 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-07 06:00 UTC F16 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-07 06:00 UTC F17 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-07 06:00 UTC F18 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-07 06:00 UTC F19 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-07 06:00 UTC F20 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-07 06:00 UTC F21 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-07 06:00 UTC F22 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-07 06:00 UTC F23 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-07 12:00 UTC F00 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-07 12:00 UTC F01 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-07 12:00 UTC F02 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-07 12:00 UTC F03 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-07 12:00 UTC F04 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-07 12:00 UTC F05 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-07 12:00 UTC F06 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-07 12:00 UTC F07 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-07 12:00 UTC F08 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-07 12:00 UTC F09 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-07 12:00 UTC F10 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-07 12:00 UTC F11 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-07 12:00 UTC F12 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-07 12:00 UTC F13 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-07 12:00 UTC F14 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-07 12:00 UTC F15 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-07 12:00 UTC F16 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-07 12:00 UTC F17 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-07 12:00 UTC F18 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-07 12:00 UTC F19 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-07 12:00 UTC F20 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-07 12:00 UTC F21 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-07 12:00 UTC F22 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-07 12:00 UTC F23 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-07 18:00 UTC F00 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-07 18:00 UTC F01 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-07 18:00 UTC F02 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-07 18:00 UTC F03 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-07 18:00 UTC F04 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-07 18:00 UTC F05 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-07 18:00 UTC F06 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-07 18:00 UTC F07 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-07 18:00 UTC F08 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-07 18:00 UTC F09 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-07 18:00 UTC F10 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-07 18:00 UTC F11 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-07 18:00 UTC F12 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-07 18:00 UTC F13 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-07 18:00 UTC F14 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-07 18:00 UTC F15 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-07 18:00 UTC F16 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-07 18:00 UTC F17 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-07 18:00 UTC F18 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-07 18:00 UTC F19 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-07 18:00 UTC F20 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-07 18:00 UTC F21 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-07 18:00 UTC F22 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-07 18:00 UTC F23 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-08 00:00 UTC F00 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-08 00:00 UTC F01 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-08 00:00 UTC F02 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-08 00:00 UTC F03 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-08 00:00 UTC F04 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-08 00:00 UTC F05 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-08 00:00 UTC F06 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-08 00:00 UTC F07 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-08 00:00 UTC F08 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-08 00:00 UTC F09 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-08 00:00 UTC F10 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-08 00:00 UTC F11 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-08 00:00 UTC F12 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-08 00:00 UTC F13 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-08 00:00 UTC F14 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-08 00:00 UTC F15 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-08 00:00 UTC F16 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-08 00:00 UTC F17 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-08 00:00 UTC F18 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-08 00:00 UTC F19 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-08 00:00 UTC F20 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-08 00:00 UTC F21 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-08 00:00 UTC F22 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-08 00:00 UTC F23 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-08 06:00 UTC F00 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-08 06:00 UTC F01 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-08 06:00 UTC F02 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-08 06:00 UTC F03 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-08 06:00 UTC F04 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-08 06:00 UTC F05 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-08 06:00 UTC F06 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-08 06:00 UTC F07 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-08 06:00 UTC F08 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-08 06:00 UTC F09 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-08 06:00 UTC F10 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-08 06:00 UTC F11 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-08 06:00 UTC F12 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-08 06:00 UTC F13 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-08 06:00 UTC F14 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-08 06:00 UTC F15 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-08 06:00 UTC F16 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-08 06:00 UTC F17 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-08 06:00 UTC F18 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-08 06:00 UTC F19 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-08 06:00 UTC F20 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-08 06:00 UTC F21 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-08 06:00 UTC F22 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-08 06:00 UTC F23 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-08 12:00 UTC F00 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-08 12:00 UTC F01 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-08 12:00 UTC F02 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-08 12:00 UTC F03 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-08 12:00 UTC F04 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-08 12:00 UTC F05 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-08 12:00 UTC F06 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-08 12:00 UTC F07 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-08 12:00 UTC F08 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-08 12:00 UTC F09 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-08 12:00 UTC F10 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-08 12:00 UTC F11 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-08 12:00 UTC F12 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-08 12:00 UTC F13 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-08 12:00 UTC F14 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-08 12:00 UTC F15 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-08 12:00 UTC F16 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-08 12:00 UTC F17 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-08 12:00 UTC F18 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-08 12:00 UTC F19 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-08 12:00 UTC F20 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-08 12:00 UTC F21 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-08 12:00 UTC F22 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-08 12:00 UTC F23 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-08 18:00 UTC F00 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-08 18:00 UTC F01 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-08 18:00 UTC F02 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-08 18:00 UTC F03 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-08 18:00 UTC F04 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-08 18:00 UTC F05 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-08 18:00 UTC F06 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-08 18:00 UTC F07 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-08 18:00 UTC F08 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-08 18:00 UTC F09 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-08 18:00 UTC F10 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-08 18:00 UTC F11 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-08 18:00 UTC F12 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-08 18:00 UTC F13 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-08 18:00 UTC F14 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-08 18:00 UTC F15 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-08 18:00 UTC F16 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-08 18:00 UTC F17 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-08 18:00 UTC F18 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-08 18:00 UTC F19 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-08 18:00 UTC F20 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-08 18:00 UTC F21 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-08 18:00 UTC F22 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-08 18:00 UTC F23 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-09 00:00 UTC F00 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-09 00:00 UTC F01 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-09 00:00 UTC F02 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-09 00:00 UTC F03 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-09 00:00 UTC F04 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-09 00:00 UTC F05 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-09 00:00 UTC F06 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-09 00:00 UTC F07 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-09 00:00 UTC F08 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-09 00:00 UTC F09 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-09 00:00 UTC F10 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-09 00:00 UTC F11 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-09 00:00 UTC F12 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-09 00:00 UTC F13 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-09 00:00 UTC F14 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-09 00:00 UTC F15 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-09 00:00 UTC F16 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-09 00:00 UTC F17 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-09 00:00 UTC F18 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-09 00:00 UTC F19 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-09 00:00 UTC F20 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-09 00:00 UTC F21 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-09 00:00 UTC F22 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-09 00:00 UTC F23 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-09 06:00 UTC F00 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-09 06:00 UTC F01 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-09 06:00 UTC F02 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-09 06:00 UTC F03 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-09 06:00 UTC F04 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-09 06:00 UTC F05 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-09 06:00 UTC F06 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-09 06:00 UTC F07 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-09 06:00 UTC F08 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-09 06:00 UTC F09 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-09 06:00 UTC F10 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-09 06:00 UTC F11 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-09 06:00 UTC F12 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-09 06:00 UTC F13 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-09 06:00 UTC F14 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2021-Oct-09 06:00 UTC F15 ┊ source=aws,

In [31]:
run = "2021-10-13 00:00" #must be 00:00 to not drop files.

In [32]:
H = FastHerbie([run], model="hrrr", fxx=np.arange(0,49,1).tolist(), save_dir='./data/.', overwrite=True)

In [33]:
H.inventory('PRATE')

,grib_message,start_byte,end_byte,range,reference_time,valid_time,variable,level,forecast_time,search_this,FILE
0,83,51922088,51922275.0,51922088-51922275,2021-10-13,2021-10-13 00:00:00,PRATE,surface,anl,:PRATE:surface:anl,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
1,83,59964613,60032993.0,59964613-60032993,2021-10-13,2021-10-13 01:00:00,PRATE,surface,1 hour fcst,:PRATE:surface:1 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
2,83,59769452,59851203.0,59769452-59851203,2021-10-13,2021-10-13 02:00:00,PRATE,surface,2 hour fcst,:PRATE:surface:2 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
3,83,60385394,60469386.0,60385394-60469386,2021-10-13,2021-10-13 03:00:00,PRATE,surface,3 hour fcst,:PRATE:surface:3 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
4,83,61083074,61175571.0,61083074-61175571,2021-10-13,2021-10-13 04:00:00,PRATE,surface,4 hour fcst,:PRATE:surface:4 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
5,83,61613739,61712215.0,61613739-61712215,2021-10-13,2021-10-13 05:00:00,PRATE,surface,5 hour fcst,:PRATE:surface:5 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
6,83,62486711,62591342.0,62486711-62591342,2021-10-13,2021-10-13 06:00:00,PRATE,surface,6 hour fcst,:PRATE:surface:6 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
7,83,63118450,63232639.0,63118450-63232639,2021-10-13,2021-10-13 07:00:00,PRATE,surface,7 hour fcst,:PRATE:surface:7 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
8,83,64619938,64742381.0,64619938-64742381,2021-10-13,2021-10-13 08:00:00,PRATE,surface,8 hour fcst,:PRATE:surface:8 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
9,83,65020594,65146394.0,65020594-65146394,2021-10-13,2021-10-13 09:00:00,PRATE,surface,9 hour fcst,:PRATE:surface:9 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
10,83,65393912,65526669.0,65393912-65526669,2021-10-13,2021-10-13 10:00:00,PRATE,surface,10 hour fcst,:PRATE:surface:10 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
11,83,65854636,65984544.0,65854636-65984544,2021-10-13,2021-10-13 11:00:00,PRATE,surface,11 hour fcst,:PRATE:surface:11 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
12,83,65743553,65873899.0,65743553-65873899,2021-10-13,2021-10-13 12:00:00,PRATE,surface,12 hour fcst,:PRATE:surface:12 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
13,83,65756048,65888824.0,65756048-65888824,2021-10-13,2021-10-13 13:00:00,PRATE,surface,13 hour fcst,:PRATE:surface:13 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
14,83,65743752,65876401.0,65743752-65876401,2021-10-13,2021-10-13 14:00:00,PRATE,surface,14 hour fcst,:PRATE:surface:14 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
15,83,65672257,65806367.0,65672257-65806367,2021-10-13,2021-10-13 15:00:00,PRATE,surface,15 hour fcst,:PRATE:surface:15 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
16,83,64964294,65095849.0,64964294-65095849,2021-10-13,2021-10-13 16:00:00,PRATE,surface,16 hour fcst,:PRATE:surface:16 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
17,83,64753464,64879859.0,64753464-64879859,2021-10-13,2021-10-13 17:00:00,PRATE,surface,17 hour fcst,:PRATE:surface:17 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
18,83,65185547,65309012.0,65185547-65309012,2021-10-13,2021-10-13 18:00:00,PRATE,surface,18 hour fcst,:PRATE:surface:18 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
19,83,63259633,63382820.0,63259633-63382820,2021-10-13,2021-10-13 19:00:00,PRATE,surface,19 hour fcst,:PRATE:surface:19 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
20,83,64399573,64521663.0,64399573-64521663,2021-10-13,2021-10-13 20:00:00,PRATE,surface,20 hour fcst,:PRATE:surface:20 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
21,83,63377537,63498279.0,63377537-63498279,2021-10-13,2021-10-13 21:00:00,PRATE,surface,21 hour fcst,:PRATE:surface:21 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
22,83,64558554,64677455.0,64558554-64677455,2021-10-13,2021-10-13 22:00:00,PRATE,surface,22 hour fcst,:PRATE:surface:22 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
23,83,64442727,64564384.0,64442727-64564384,2021-10-13,2021-10-13 23:00:00,PRATE,surface,23 hour fcst,:PRATE:surface:23 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
24,83,64412929,64541241.0,64412929-64541241,2021-10-13,2021-10-14 00:00:00,PRATE,surface,24 hour fcst,:PRATE:surface:24 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
25,83,63438663,63565022.0,63438663-63565022,2021-10-13,2021-10-14 01:00:00,PRATE,surface,25 hour fcst,:PRATE:surface:25 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
26,83,63200718,63322614.0,63200718-63322614,2021-10-13,2021-10-14 02:00:00,PRATE,surface,26 hour fcst,:PRATE:surface:26 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
27,83,64759065,64877884.0,64759065-64877884,2021-10-13,2021-10-14 03:00:00,PRATE,surface,27 hour fcst,:PRATE:surface:27 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
28,83,64972097,65088269.0,64972097-65088269,2021-10-13,2021-10-14 04:00:00,PRATE,surface,28 hour fcst,:PRATE:surface:28 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
29,83,64964927,65080016.0,64964927-65080016,2021-10-13,2021-10-14 05:00:00,PRATE,surface,29 hour fcst,:PRATE:surface:29 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
30,83,65035123,65151753.0,65035123-65151753,2021-10-13,2021-10-14 06:00:00,PRATE,surface,30 hour fcst,:PRATE:surface:30 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
31,83,64798322,64910260.0,64798322-64910260,2021-10-13,2021-10-14 07:00:00,PRATE,surface,31 hour fcst,:PRATE:surface:31 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
32,83,64590520,64704250.0,64590520-64704250,2021-10-13,2021-10-14 08:00:00,PRATE,surface,32 hour fcst,:PRATE:surface:32 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
33,83,64778947,64892156.0,64778947-64892156,2021-10-13,2021-10-14 09:00:00,PRATE,surface,33 hour fcst,:PRATE:surface:33 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
34,83,64782220,64896923.0,64782220-64896923,2021-10-13,2021-10-14 10:00:00,PRATE,surface,34 hour fcst,:PRATE:surface:34 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
35,83,64367689,64477771.0,64367689-64477771,2021-10-13,2021-10-14 11:00:00,PRATE,surface,35 hour fcst,:PRATE:surface:35 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
36,83,64415180,64525154.0,64415180-64525154,2021-10-13,2021-10-14 12:00:00,PRATE,surface,36 hour fcst,:PRATE:surface:36 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
37,83,64326999,64436166.0,64326999-64436166,2021-10-13,2021-10-14 13:00:00,PRATE,surface,37 hour fcst,:PRATE:surface:37 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
38,83,64253171,64360369.0,64253171-64360369,2021-10-13,2021-10-14 14:00:00,PRATE,surface,38 hour fcst,:PRATE:surface:38 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
39,83,64011938,64112523.0,64011938-64112523,2021-10-13,2021-10-14 15:00:00,PRATE,surface,39 hour fcst,:PRATE:surface:39 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
40,83,63202131,63294858.0,63202131-63294858,2021-10-13,2021-10-14 16:00:00,PRATE,surface,40 hour fcst,:PRATE:surface:40 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
41,83,62821095,62905971.0,62821095-62905971,2021-10-13,2021-10-14 17:00:00,PRATE,surface,41 hour fcst,:PRATE:surface:41 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
42,83,62370426,62455116.0,62370426-62455116,2021-10-13,2021-10-14 18:00:00,PRATE,surface,42 hour fcst,:PRATE:surface:42 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
43,83,62406502,62491514.0,62406502-62491514,2021-10-13,2021-10-14 19:00:00,PRATE,surface,43 hour fcst,:PRATE:surface:43 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
44,83,62866780,62949233.0,62866780-62949233,2021-10-13,2021-10-14 20:00:00,PRATE,surface,44 hour fcst,:PRATE:surface:44 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
45,83,62922716,63005089.0,62922716-63005089,2021-10-13,2021-10-14 21:00:00,PRATE,surface,45 hour fcst,:PRATE:surface:45 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
46,83,62695395,62777408.0,62695395-62777408,2021-10-13,2021-10-14 22:00:00,PRATE,surface,46 hour fcst,:PRATE:surface:46 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
47,83,62371160,62449516.0,62371160-62449516,2021-10-13,2021-10-14 23:00:00,PRATE,surface,47 hour fcst,:PRATE:surface:47 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
48,83,61998072,62071255.0,61998072-62071255,2021-10-13,2021-10-15 00:00:00,PRATE,surface,48 hour fcst,:PRATE:surface:48 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...

In [34]:
ss2 = "(:TMP:2 m|:RH:2 m|:TCDC:entire|LTNG|PRATE)"
H.inventory(ss2)

/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)

,grib_message,start_byte,end_byte,range,reference_time,valid_time,variable,level,forecast_time,search_this,FILE
0,59,27906663,27906850.0,27906663-27906850,2021-10-13,2021-10-13,LTNG,entire atmosphere,anl,:LTNG:entire atmosphere:anl,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
1,71,36904597,38093638.0,36904597-38093638,2021-10-13,2021-10-13,TMP,2 m above ground,anl,:TMP:2 m above ground:anl,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
2,75,41784887,43311345.0,41784887-43311345,2021-10-13,2021-10-13,RH,2 m above ground,anl,:RH:2 m above ground:anl,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
3,83,51922088,51922275.0,51922088-51922275,2021-10-13,2021-10-13,PRATE,surface,anl,:PRATE:surface:anl,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
4,116,70931218,71880885.0,70931218-71880885,2021-10-13,2021-10-13,TCDC,entire atmosphere,anl,:TCDC:entire atmosphere:anl,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
...,...,...,...,...,...,...,...,...,...,...,...
240,59,37345262,37366417.0,37345262-37366417,2021-10-13,2021-10-15,LTNG,entire atmosphere,48 hour fcst,:LTNG:entire atmosphere:48 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
241,71,46860465,48039497.0,46860465-48039497,2021-10-13,2021-10-15,TMP,2 m above ground,48 hour fcst,:TMP:2 m above ground:48 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
242,75,51787042,53361261.0,51787042-53361261,2021-10-13,2021-10-15,RH,2 m above ground,48 hour fcst,:RH:2 m above ground:48 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
243,83,61998072,62071255.0,61998072-62071255,2021-10-13,2021-10-15,PRATE,surface,48 hour fcst,:PRATE:surface:48 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
244,119,86498407,87266645.0,86498407-87266645,2021-10-13,2021-10-15,TCDC,entire atmosphere,48 hour fcst,:TCDC:entire atmosphere:48 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...

In [35]:
fp = H.download(ss2)

/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)

In [36]:
fp

[PosixPath('data/hrrr/20211013/subset_a0ef6940__hrrr.t00z.wrfsfcf00.grib2'),
 PosixPath('data/hrrr/20211013/subset_a069411d__hrrr.t00z.wrfsfcf17.grib2'),
 PosixPath('data/hrrr/20211013/subset_a0be411d__hrrr.t00z.wrfsfcf13.grib2'),
 PosixPath('data/hrrr/20211013/subset_a0b8411d__hrrr.t00z.wrfsfcf15.grib2'),
 PosixPath('data/hrrr/20211013/subset_a0c5411d__hrrr.t00z.wrfsfcf08.grib2'),
 PosixPath('data/hrrr/20211013/subset_a09e411d__hrrr.t00z.wrfsfcf09.grib2'),
 PosixPath('data/hrrr/20211013/subset_a0c7411d__hrrr.t00z.wrfsfcf07.grib2'),
 PosixPath('data/hrrr/20211013/subset_a0a4411d__hrrr.t00z.wrfsfcf11.grib2'),
 PosixPath('data/hrrr/20211013/subset_a018411d__hrrr.t00z.wrfsfcf14.grib2'),
 PosixPath('data/hrrr/20211013/subset_a0e46940__hrrr.t00z.wrfsfcf01.grib2'),
 PosixPath('data/hrrr/20211013/subset_a0bc411d__hrrr.t00z.wrfsfcf19.grib2'),
 PosixPath('data/hrrr/20211013/subset_a0b2411d__hrrr.t00z.wrfsfcf06.grib2'),
 PosixPath('data/hrrr/20211013/subset_a089411d__hrrr.t00z.wrfsfcf18.grib2'),
 PosixPath('data/hrrr/20211013/subset_a015411d__hrrr.t00z.wrfsfcf03.grib2'),
 PosixPath('data/hrrr/20211013/subset_a021411d__hrrr.t00z.wrfsfcf02.grib2'),
 PosixPath('data/hrrr/20211013/subset_a0d4411d__hrrr.t00z.wrfsfcf10.grib2'),
 PosixPath('data/hrrr/20211013/subset_a04b411d__hrrr.t00z.wrfsfcf04.grib2'),
 PosixPath('data/hrrr/20211013/subset_a0be411d__hrrr.t00z.wrfsfcf16.grib2'),
 PosixPath('data/hrrr/20211013/subset_a01a411d__hrrr.t00z.wrfsfcf05.grib2'),
 PosixPath('data/hrrr/20211013/subset_a012411d__hrrr.t00z.wrfsfcf12.grib2'),
 PosixPath('data/hrrr/20211013/subset_a020411d__hrrr.t00z.wrfsfcf20.grib2'),
 PosixPath('data/hrrr/20211013/subset_a00e411d__hrrr.t00z.wrfsfcf24.grib2'),
 PosixPath('data/hrrr/20211013/subset_a01e411d__hrrr.t00z.wrfsfcf27.grib2'),
 PosixPath('data/hrrr/20211013/subset_a0cc411d__hrrr.t00z.wrfsfcf26.grib2'),
 PosixPath('data/hrrr/20211013/subset_a0d2411d__hrrr.t00z.wrfsfcf28.grib2'),
 PosixPath('data/hrrr/20211013/subset_a0b5411d__hrrr.t00z.wrfsfcf23.grib2'),
 PosixPath('data/hrrr/20211013/subset_a011411d__hrrr.t00z.wrfsfcf22.grib2'),
 PosixPath('data/hrrr/20211013/subset_a0ce411d__hrrr.t00z.wrfsfcf29.grib2'),
 PosixPath('data/hrrr/20211013/subset_a01b411d__hrrr.t00z.wrfsfcf33.grib2'),
 PosixPath('data/hrrr/20211013/subset_a060411d__hrrr.t00z.wrfsfcf30.grib2'),
 PosixPath('data/hrrr/20211013/subset_a030411d__hrrr.t00z.wrfsfcf25.grib2'),
 PosixPath('data/hrrr/20211013/subset_a086411d__hrrr.t00z.wrfsfcf21.grib2'),
 PosixPath('data/hrrr/20211013/subset_a0f8411d__hrrr.t00z.wrfsfcf31.grib2'),
 PosixPath('data/hrrr/20211013/subset_a01e411d__hrrr.t00z.wrfsfcf35.grib2'),
 PosixPath('data/hrrr/20211013/subset_a058411d__hrrr.t00z.wrfsfcf32.grib2'),
 PosixPath('data/hrrr/20211013/subset_a00e411d__hrrr.t00z.wrfsfcf36.grib2'),
 PosixPath('data/hrrr/20211013/subset_a03a411d__hrrr.t00z.wrfsfcf37.grib2'),
 PosixPath('data/hrrr/20211013/subset_a0be411d__hrrr.t00z.wrfsfcf34.grib2'),
 PosixPath('data/hrrr/20211013/subset_a00f411d__hrrr.t00z.wrfsfcf38.grib2'),
 PosixPath('data/hrrr/20211013/subset_a048411d__hrrr.t00z.wrfsfcf39.grib2'),
 PosixPath('data/hrrr/20211013/subset_a064411d__hrrr.t00z.wrfsfcf40.grib2'),
 PosixPath('data/hrrr/20211013/subset_a0de411d__hrrr.t00z.wrfsfcf41.grib2'),
 PosixPath('data/hrrr/20211013/subset_a0ac411d__hrrr.t00z.wrfsfcf46.grib2'),
 PosixPath('data/hrrr/20211013/subset_a061411d__hrrr.t00z.wrfsfcf45.grib2'),
 PosixPath('data/hrrr/20211013/subset_a0c2411d__hrrr.t00z.wrfsfcf44.grib2'),
 PosixPath('data/hrrr/20211013/subset_a01c411d__hrrr.t00z.wrfsfcf48.grib2'),
 PosixPath('data/hrrr/20211013/subset_a0e4411d__hrrr.t00z.wrfsfcf47.grib2'),
 PosixPath('data/hrrr/20211013/subset_a069411d__hrrr.t00z.wrfsfcf43.grib2'),
 PosixPath('data/hrrr/20211013/subset_a0e7411d__hrrr.t00z.wrfsfcf42.grib2')]

In [37]:
ds = xr.open_mfdataset(fp, combine='nested', concat_dim='valid_time')

/tmp/ipykernel_1588697/3885475503.py:1: FutureWarning: In a future version of xarray the default value for coords will change from coords='different' to coords='minimal'. This is likely to lead to different results when multiple datasets have matching variables with overlapping values. To opt in to new defaults and get rid of these warnings now use `set_options(use_new_combine_kwarg_defaults=True) or set coords explicitly.
  ds = xr.open_mfdataset(fp, combine='nested', concat_dim='valid_time')

In [38]:
ds

<xarray.Dataset> Size: 2GB
Dimensions:            (valid_time: 49, y: 1059, x: 1799)
Coordinates:
  * valid_time         (valid_time) datetime64[ns] 392B 2021-10-13 ... 2021-1...
    time               datetime64[ns] 8B 2021-10-13
    step               (valid_time) timedelta64[ns] 392B 00:00:00 ... 1 days ...
    atmosphere         float64 8B 0.0
    latitude           (y, x) float64 15MB dask.array<chunksize=(1059, 1799), meta=np.ndarray>
    longitude          (y, x) float64 15MB dask.array<chunksize=(1059, 1799), meta=np.ndarray>
    heightAboveGround  float64 8B 2.0
    surface            float64 8B 0.0
Dimensions without coordinates: y, x
Data variables:
    ltng               (valid_time, y, x) float32 373MB dask.array<chunksize=(1, 1059, 1799), meta=np.ndarray>
    t2m                (valid_time, y, x) float32 373MB dask.array<chunksize=(1, 1059, 1799), meta=np.ndarray>
    r2                 (valid_time, y, x) float32 373MB dask.array<chunksize=(1, 1059, 1799), meta=np.ndarray>
    prate              (valid_time, y, x) float32 373MB dask.array<chunksize=(1, 1059, 1799), meta=np.ndarray>
    tcc                (valid_time, y, x) float32 373MB dask.array<chunksize=(1, 1059, 1799), meta=np.ndarray>
Attributes:
    GRIB_edition:            2
    GRIB_centre:             kwbc
    GRIB_centreDescription:  US National Weather Service - NCEP
    GRIB_subCentre:          0
    Conventions:             CF-1.7
    institution:             US National Weather Service - NCEP
    history:                 2026-03-25T16:20 GRIB to CDM+CF via cfgrib-0.9.1...

In [39]:
filename = 'nullhrrr.nc'

In [40]:
ds.to_netcdf(filename)

# Start Here! Do not redownload

In [41]:
ds = xr.open_dataset('nullhrrr.nc') # run first
ds

sh: 1: getfattr: not found

<xarray.Dataset> Size: 2GB
Dimensions:            (valid_time: 49, y: 1059, x: 1799)
Coordinates:
  * valid_time         (valid_time) datetime64[ns] 392B 2021-10-13 ... 2021-1...
    time               datetime64[ns] 8B ...
    step               (valid_time) timedelta64[ns] 392B ...
    atmosphere         float64 8B ...
    latitude           (y, x) float64 15MB ...
    longitude          (y, x) float64 15MB ...
    heightAboveGround  float64 8B ...
    surface            float64 8B ...
Dimensions without coordinates: y, x
Data variables:
    ltng               (valid_time, y, x) float32 373MB ...
    t2m                (valid_time, y, x) float32 373MB ...
    r2                 (valid_time, y, x) float32 373MB ...
    prate              (valid_time, y, x) float32 373MB ...
    tcc                (valid_time, y, x) float32 373MB ...
Attributes:
    GRIB_edition:            2
    GRIB_centre:             kwbc
    GRIB_centreDescription:  US National Weather Service - NCEP
    GRIB_subCentre:          0
    Conventions:             CF-1.7
    institution:             US National Weather Service - NCEP
    history:                 2026-03-25T16:20 GRIB to CDM+CF via cfgrib-0.9.1...

In [42]:
ds = ds.sortby('valid_time')
ds

<xarray.Dataset> Size: 2GB
Dimensions:            (valid_time: 49, y: 1059, x: 1799)
Coordinates:
  * valid_time         (valid_time) datetime64[ns] 392B 2021-10-13 ... 2021-1...
    time               datetime64[ns] 8B ...
    step               (valid_time) timedelta64[ns] 392B ...
    atmosphere         float64 8B ...
    latitude           (y, x) float64 15MB ...
    longitude          (y, x) float64 15MB ...
    heightAboveGround  float64 8B ...
    surface            float64 8B ...
Dimensions without coordinates: y, x
Data variables:
    ltng               (valid_time, y, x) float32 373MB ...
    t2m                (valid_time, y, x) float32 373MB ...
    r2                 (valid_time, y, x) float32 373MB ...
    prate              (valid_time, y, x) float32 373MB ...
    tcc                (valid_time, y, x) float32 373MB ...
Attributes:
    GRIB_edition:            2
    GRIB_centre:             kwbc
    GRIB_centreDescription:  US National Weather Service - NCEP
    GRIB_subCentre:          0
    Conventions:             CF-1.7
    institution:             US National Weather Service - NCEP
    history:                 2026-03-25T16:20 GRIB to CDM+CF via cfgrib-0.9.1...